export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"
export ZSH_CACHE_DIR="${ZSH_CACHE_DIR:-$ZSH/cache}"

ZSH_THEME="robbyrussell"

plugins=(git
z
zsh-autosuggestions
zsh-syntax-highlighting
zsh-shift-select
fzf
macos
)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/export.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/misc.zsh
[[ -f $HOME/.zsh/work.zsh ]] && source $HOME/.zsh/work.zsh